version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - ./config/backend.env
    hostname: backend
    volumes:
      - ./source:/source:cached
